json.id book.id
json.access_no book.access_no
json.book_name book.book_name
json.isbn book.isbn
json.cupboard_no book.cupboard_no
json.shelf_no book.shelf_no
json.price book.price
json.authors book.authors.map(&:author_name)
json.status book.availability